
// Currently using these Javascript objects as my db since I am unable to download anything on this pc and thus do not have access to a real db using this computer
// but need to eventually re-write this on a different pc using a real database
// That way, I can Add/Remove words through the UI instead of having to handle it here in the code
// Then I can also create a db for user accounts, and each user could have a base db, but add/remove their own words

var oldWords = {	

	//IDIOMS--------------------------------------------------
	"a cal y canto": "under lock and key",
	"conocer el paño": "to know what's what",
	"que lata": "how boring",
	"puesto que": "since",
	"de golpe": "all at once",
	"meter la pata": "to blunder",
	"en conjunto": "as a whole",
	"a lo mejor": "maybe",	
	"de bruces": "flat on one's face",
	"ponerse las pilas": "to get one's act together",
	"de primera": "first class",
	"echar de menos": "to miss",
	"echar mano de": "to fall back on",
	"pese a haber": "despite having",
	"dar por sentado": "to take for granted",
    "hoy en día": "nowadays",
	"por sí solas": "on their own",
	"de par en par": "wide open",
	"en cuanto a": "with regard to",
	"por si": "in case",
    "desde luego": "certainly",
	"más te vale": "you'd better",
	"vale la pena": "it's worth it",	
	"a sabiendas":"knowingly",
	"cada cuánto": "how often",
	"sin ánimo de lucro": "nonprofit",

	//PREPOSITIONS/CONJUNCTIONS/OTHER-------------------------
    "sobre": "about",
    "acerca de": "about",
    "según": "according to",
    "desde": "since",
    "entonces": "then",
    "casi": "almost",
    "cualquier": "any/whichever",
    "ningún": "any/negative",
    "algún": "any/some",
	"aun": "even",
    "aún": "still",
    "mayor": "older",
    "mejor": "better",
    "menor": "younger",
    "peor": "worse",
    "tan": "so",
    "tanto": "so much",
    "adelante": "forward",
    "demasiado": "too much",
    "jamás": "never!",
    "ya": "already/anymore",
    "algo": "something",
    "así": "like this",
    "todavía": "still",
    "hacia": "toward",
    "siquiera": "at least",
    "bastante": "enough/rather",
    "a través de": "through",
    "acá": "here",
    "acabar de": "just",
	"detrás": "behind/after",
    "atrás": "behind/backwards",
    "tras": "after",
    "a medida que": "as",
    "tal": "such",
    "a punto de": "about to",
    "a menudo": "often",
    "incluso": "even",
    "demás": "other",
	"a partir de": "as of/from",
	"se trata de": "it's about",
	"un rato": "a while",
	"a eso de": "around",
	"entrante": "next",
	"a estas alturas": "by now/at this stage",
	"por poco": "almost/no matter how little",
	"en torno": "around",
	"encima": "above",
	"temprano": "early",
	"acaso": "perhaps",
	"cotidiano": "daily",
	"en cuanto": "as soon as",
	"tan solo": "just/only",
	"de vuelta": "back/again",
	"en llamas": "in flames",
	"ojalá": "hopefully",
	"mediante": "by means of",
    "asimismo": "also/likewise",


	
	"en vez de": "instead of",
    "ya que": "now that/since",
    "de hecho": "in fact",
    "a pesar de": "in spite of",
    "por lo tanto": "therefore",
	"aun así": "even then",
    "aunque": "although",
    "además": "besides",	
	"en cambio": "instead",
	"pese a que": "even though",
	"más bien": "rather",
	"sin embargo": "however",
    "no obstante": "however",
	"si bien": "although",
	
		
	// ADJECTIVES------------------------------------------------
	"aledaño": "neighboring",
	"bullicioso": "noisy",
	"grácil": "graceful",
	"lúgubre": "dismal",
	"paulatino": "gradual",
	"retraído": "withdrawn",
	"terco": "stubborn",
	"acaudalado": "wealthy",
	"enajenado": "alienated",
	"leal": "loyal",		
	"raro": "strange",
	"apuesto": "handsome",
	"de repuesto": "spare",
	"suelto": "loose",
	"leve": "slight",
	"perspicaz": "sharp/intelligent",
	"abrumador": "overwhelming",	
	"estimada": "dear",
	"educado": "polite",
	"atrevido": "adventurous",
    "atrasado": "late",
	"hondo": "deep",
	"gelida": "frigid",
    "escabroso": "rough",
    "pleno": "full",
    "ligero": "light/subtle",
    "alejado": "distant",
    "titubeante": "hesitant",
    "desenfrenado": "wild/unbridled",
    "desquiciado": "deranged",
    "nítida": "sharp/clear",
    "menudo": "small/insignificant",
    "disponible": "available",
    "dispuesto": "ready",
    "pasajero": "passenger/fleeting",
    "comodo": "comfortable",
    "herido": "wounded",
	"matutino": "morning",
    "eólico": "wind",
 	"lodoso": "muddy",
    "silvestre": "wild/natural",
    "salvaje": "wild/savage",
    "ciego": "blind",	
	"abultado": "bulky/inflated",
	"angosto": "narrow",
	"bochornoso": "muggy/stuffy",
	"espeso": "thick",
	"hortera": "tacky",
	"ligado": "bound",
	"maduro": "mature",
	"mordaz": "scathing",
	"nocivo": "harmful",
	"parecido": "similar",
	"pudiente": "wealthy",
	"pulcro": "neat/tidy",
	"rudo": "rude/rough",
	"semejante": "similar",
	"tierno": "tender",
	"rudo": "rough",
	"vigente": "in force",	
	"asequible": "affordable/achievable",
	"entrañable": "close/dear",
	"hábil": "working",
	"lozano": "healthy/lush",
	"sordo": "deaf",
	"entero": "whole/entire",
	"grato": "pleasant",
	"maldito": "darn/damn",
    "ahíto": "full",
    "áspero": "rough",
    "ensimismada": "absorbed/self-absorbed",
    "estrafalario": "eccentric",
    "estrambótico": "outlandish",		
	"exigente": "demanding",
	"rapaz": "predatory",
    "altivo": "haughty",
    "apabullante": "overwhelming",
    "maloliente": "stinking",
    "súbito": "sudden",
	"adinerado": "wealthy",
	"idóneo": "suitable",
	"espantoso": "horrifying",
	"restante": "remaining",
	"desharrapado": "ragged",
	"aleatorio": "random",
	"bursátil": "stock market",
	"funesto": "ill-fated",
	"impávido": "impassive/undaunted",
	"socarrón": "sarcastic",
	"sombrío": "gloomy",
	"tajante": "categorical",
	"venidero": "coming",
	"añoso": "age-old",
	"chulo": "cool",
	"costeño": "coastal",
	"despiadado": "ruthless",
	"enmarañado": "tangled",
	"jopé": "darn",
	"larguirucho": "lanky",
	"burdo": "clumsy",
	"calvo": "bald",
	"contundente": "blunt",
	"demoledor": "devastating",
	"ileso": "unharmed",
	"insólito": "unusual",
	"nimia": "trivial",
	"peluche": "stuffed/plush",
	"peludo": "hairy",
	"rizado": "curly",
	"testarudo": "stubborn",
	"tosco": "crude",
	"digno": "worthy",
	"tenebroso": "gloomy/dark",
	"tieso": "stiff",
	"mandón": "bossy",
	"macizo": "solid",	
	"ufano": "proud",
	"ajetreado": "busy",
	"renuente": "reluctant",
	"sobrante": "surplus",
	"empinada": "steep",
	"estrecho": "narrow",
	"ajeno": "foreign/other",
	"llano": "flat",
	"asombroso": "amazing",
	"medular": "fundamental",
	"resbaloso": "slippery",
	"escarpada": "steep",
	"espeluznante": "terrifying",
	"torpe": "clumsy",
	"estancado": "stagnant",
	"fiable": "reliable",
	"descarado": "shameless/blatant",
	"flaco": "skinny",
	"despistado": "absent-minded",
	"blando": "soft",
	"agrio": "sour",	
	"amargo": "bitter",
	"escueto": "concise/plain",
	"estrepitoso": "spectacular/noisy",
	"hosco": "sullen",
	"reacio": "reluctant",
	"rentable": "profitable",
	"subyacente": "underlying",
	"lugareño": "local",
	"parlanchín": "talkative",
	"pujante": "thriving/vigorous",
	"tacaño": "stingy",
	"tibio": "lukewarm",
	
	// ADVERBS------------------------------------------------
	"de repente": "suddenly",
    "hace poco": "recently",
    "dizque": "supposedly/apparently",
    "apenas": "barely",
	"de buena gana": "willingly",
	"enseguida": "immediately",


	// VERBS------------------------------------------------
    "regalar": "to give away",
    "ubicar": "to locate",
    "involucrar": "to involve",
    "abarcar": "to cover/take on",
    "difundir": "to spread",
	"añadir": "to add",
    "engañar": "to deceive",
    "probar": "to test",
    "surgir": "to arise",
    "amenazar": "to threaten",
    "reclutar": "to recruit",
    "desbancar": "to oust/replace",
    "entregar": "to deliver/submit",
    "apresurar": "to hurry",
	"alardear": "to boast",
    "enmarcar": "to frame",
    "instar": "to urge",
    "atropellar": "to run over",
    "huir": "to escape",
    "confiar": "to confide/trust",
    "quedar": "to remain",
    "tratar de": "to try",
    "tratar": "to treat",
    "alcanzar": "to reach",
    "perder": "to lose",
    "pedir": "to ask/order",	
    "lograr": "to achieve",
    "cumplir": "to achieve",
    "venir": "to come",
    "volver": "to return",
    "llegar": "to arrive",
    "dejar": "to leave behind/let",
    "acabar": "to end/finish",
    "amargar": "to make bitter",
    "susurrar": "to whisper",
    "golpear": "to hit",
    "trenzar": "to braid",
    "pertenecer": "to belong to",
    "colgar": "to hang",
    "rogar": "to beg",
    "pegar": "to stick/hit",
    "atar": "to tie/bind",
    "apagar": "to turn off",
    "colocar": "to place",
    "evitar": "to avoid",
    "borrar": "to erase",
    "enlutar": "to sadden",
    "luchar": "to struggle",
    "arrasar": "to destroy",
    "allanar": "to flatten",
    "compartir": "to share",
    "despertar": "to awake",
    "asustar": "to frighten",
    "desatender": "to neglect",
    "disparar": "to shoot",
    "alquilar": "to rent",
	"paliar": "to ease/relieve",
	"topar": "to run into",
	"fruncir": "to furrow",
	"estrenar": "to premiere",
	"abogar": "to advocate",
	"empañar": "to tarnish",
	"arraigar": "to take root",
	"gozar": "to enjoy",
	"descomponerse": "to break down",
	"jalar": "to pull",
	"arrancar": "to pull out/start up",
	"estallar": "to explode",
	"encarar": "to confront",
	"burlar": "to taunt/mock",
	"escoger": "to choose",
	"abuchear": "to boo",
	"chismear": "to gossip",
	"cotillear": "to gossip",
	"cabalgar": "to ride",
	"desplegar": "to unfold/spread",
    "recoger": "to pick up/gather",
	"sujetar": "to hold/fasten",
	"desgarrar": "to tear",
	"darse por vencido": "to give up",
	"coquetear": "to flirt",
	"lucir": "to shine",
	"sollozar": "to sob",
	"apenar": "to sadden",
	"platicar": "to discuss/converse",
	"vencer": "to defeat",
	"emprender": "to undertake",
	"atrasar": "to delay",
	"aferrarse": "to grasp",
	"padecer": "to suffer",
	"anhelar": "to long/yearn for",
	"despojar": "to strip",
	"quejarse": "to complain",
	"apretar": "to press/squeeze",
	"acontecer": "to happen",
	"registrar": "to search",	
	"aprobar": "to pass/approve",
	"galardonar": "to award",
	"soler": "to tend to/use to",
	"suprimir": "to eliminate",
	"mojar": "to get wet",
	"dejar caer": "to drop",
	"agarrar": "to grab",
	"respaldar": "to back up/support",
	"fallar": "to fail",
	"arrendar": "to rent",
	"agradecer": "to thank",
	"hundir": "to sink",
	"marearse": "to get sick/dizzy",
	"meterse": "to get into",	
	"asentir": "to agree/nod",
	"acechar": "to spy on",
	"equivocarse": "to make a mistake",
	"quebrar": "to break",
	"quemar": "to burn",
	"sacudir": "to shake",
	"criar": "to raise",
	"arreglar": "to fix",
	"adivinar": "to guess",
	"doblar": "to fold/turn",
	"averiguar": "to find out",
	"machacar": "to crush",
	"vacilar": "to hesitate",
    "apostar": "to bet",
    "destacar": "to emphasize",
    "proferir": "to utter",
    "lidiar": "to deal with",	
    "multar": "to fine",
	"merecer": "to deserve",
	"sacar": "to take out/remove",
	"subir": "to go up",
	"aprovechar": "to take advantage of",
	"fingir": "to pretend",
	"desmayar": "to faint",
	"envejecer": "to grow old",	
	"suspirar": "to sigh",
	"cazar": "to hunt",
	"decepcionar": "to disappoint",
	"orar": "to pray",
	"deprimir": "to depress",
	"despedirse": "to say goodbye/fire",
	"mudarse": "to move",
	"abrazar": "to hug",
	"redactar": "to write",
	"aguantar": "to bear/put up with",
	"planchar": "to iron",
	"empatar": "to tie",
	"avergonzar": "to embarrass/shame",
	"aterrizar": "to land",
	"acostar": "to go to bed/lay down",
	"elogiar": "to praise",
	"brotar": "to sprout",
	"mandar": "to order/send",
	"desvanecer": "to dispel/fade",
	"descartar": "to rule out",
	"zanjar": "to settle/resolve",
	"vincular": "to link",
	"sudar": "to sweat",
	"pelear": "to fight",
	"chocar": "to crash",
	"desatar": "to trigger/unleash",
	"gruñir": "to growl",
	"afilar": "to sharpen",
	"otorgar": "to grant",
	"sembrar": "to plant/scatter/sow",
	"tartamudear": "to stutter",
	"raptar": "to kidnap",
	"ahogar": "to drown",
	"apuñalar": "to stab",
	"frenar": "to brake",
	"atreverse": "to dare",
	"enmendar": "to correct",
	"gastar": "to spend",
	"enajenar": "to entrance/alienate",
	"augurar": "to predict",
	"avisar": "to warn",
	"vaticinar": "to predict",
	"agredir": "to attack",
	"plantear": "to suggest",
	"despegar": "to take off",
	"aniquilar": "to annihilate",
	"derrumbar": "to demolish",
	"enrumbar": "to set off",
	"acudir": "to come",
	"escabullirse": "to slip away",
	"rechazar": "to reject",
	"ansiar": "to long/yearn for",
	"socavar": "to undermine",
	"conseguir": "to get/obtain",
	"festejar": "to celebrate",
	"toser": "to cough",
	"reprimir": "to suppress",
	"canalizar": "to channel",
	"vetar": "to veto",
	"ahorrarse": "to avoid/save",
	"agotar": "to exhaust",
	"prestar": "to lend",
	"soltar": "to drop/let go/loosen",
	"enterar": "to inform",
	"tapar": "to cover",
	"aportar": "to contribute",
	"desprender": "to detach/give off",
	"posar": "to put down/lay down",
	"coser": "to sew",
	"lucrarse": "to profit",
	"mermar": "to diminish",
	"acceder": "to access/agree",
	"alentar": "to encourage",
	"delatar": "to denounce/inform on",
	"desmoronarse": "to crumble",
	"digerir": "to digest/assimilate",
	"empapar": "to soak",
	"enchufar": "to plug in",
	"hartar": "to get tired of",
	"moler": "to grind/mill",
	"recabar": "to collect/demand",
	"recostar": "to lean",
	"rezar": "to pray",
	"recurrir": "to turn to/resort to",
	"sopesar": "to weigh",
	"adelgazar": "to lose weight",
	"afinar": "to tune/refine",
	"agobiar": "to overwhelm",
	"agudizar": "to sharpen/worsen",
	"ahondar": "to deepen",
	"alabar": "to praise",
	"aplastar": "to crush",
	"aquejar": "to afflict",
	"arañar": "to scratch",
	"asomar": "to stick out",
	"ataviar": "to dress up",
	"atizar": "to poke",
	"azotar": "to whip",
	"brincar": "to jump",
	"carecer": "to lack",
	"cerner": "to sift",
	"cobrar": "to charge for",
	"comprobar": "to check/prove",
	"difuminar": "to blur",
	"encajar": "to fit",
	"encarnar": "to embody",
	"enderezar": "to straighten",
	"engullir": "to gobble",
	"escarcir": "to scatter/spread",
	"esparcir": "to scatter/spread",
	"fomentar": "to encourage",
	"fundir": "to melt",
	"latir": "to beat",
	"merodear": "to prowl",
	"pecar": "to sin",
	"ralentizar": "to slow down",
	"rastrear": "to track/trail",
	"recaudar": "to collect",
	"recelar": "to suspect",
	"rendir": "to produce",
	"rendirse": "to quit",
	"regir": "to govern",
	"resbalar": "to slip",
	"resaltar": "to highlight",
	"retirar": "to remove",
	"roncar": "to snore",
	"talar": "to cut down",
	"teñir": "to stain/tinge",
	"trepar": "to climb",
	"tumbar": "to knock down",
	"tumbarse": "to lie down/stretch out",
	"untar": "to smear",
	"vendar": "to bandage",
	"volcar": "to tip over",
	"yacer": "to lie",
	"zambullir": "to dip",
	"albergar": "to house/harbor",
	"aplazar": "to postpone",
	"añorar": "to long/yearn for",
	"barrer": "to sweep",
	"brindarse": "to offer/toast",
	"desconchar": "to chip",
	"desmigajar": "to crumble",
	"emborrachar": "to get drunk",
	"estorbar": "to impede/bother",
	"exigir": "to demand",
	"hervir": "to boil",
	"pitar": "to whistle",
	"presenciar": "to witness",
	"recetar": "to prescribe",
	"rociar": "to spray/sprinkle",
	"sanar": "to cure/heal",
	"subsanar": "to excuse/rectify",
	"sufragar": "to vote",
	"deleitar": "to delight",
	"despejar": "to clear",
	"enfadar": "to upset",
	"enmudecer": "to silence",
	"ensombrecer": "to darken",
	"escupir": "to spit",
	"esquivar": "to dodge/avoid",
	"recalcar": "to stress/emphasize",
	"velar": "to keep vigil over",
	"abatir": "to take down",
	"atajarse": "to stop short",
	"acordarse": "to remember",
	"apetecer": "to feel like",
	"arrastrar": "to drag",
	"avenir": "to reconcile",
	"constatar": "to confirm",
	"chantajear": "to blackmail",
	"derramar": "to spill/spread",
	"deslizar": "to slide",
	"destellar": "to sparkle",
	"desterrar": "to banish/exile",
	"embriagarse": "to get drunk",
	"gemir": "to moan/groan",
    "jurar": "to swear",
    "lamer": "to lick",
    "menear": "to shake",
    "picar": "to bite/sting",
    "picotear": "to peck",
    "relamerse": "to lick one's lips",
    "soportar": "to endure",
    "zampar": "to eat greedily",
	"arrojar": "to throw",
	"repartir": "to distribute",
	"retratar": "to photograph/portray",
    "abarrotar": "to pack",
    "acertar": "to guess correctly",
    "desentrañar": "to figure out/unravel",
    "despotricar": "to rant",
    "nutrir": "to nourish",
    "resquebrajar": "to crack",
    "vislumbrar": "to discern",
	"acuñar": "to coin",
	"afianzarse": "to become established",
	"apoderar": "to authorize",
	"apoderarse": "to seize",
	"atañer": "to concern",
	"atestar": "to pack/cram",
	"colarse": "to sneak in",
	"cosechar": "to harvest",
	"cosquillear": "to tickle",
	"deparar": "to bring",
	"disponerse": "to prepare",
	"distar": "to be far from",
	"embrutecer": "to daze/dull",
	"empalagar": "to be too sweet",
	"empujar": "to push",
	"enterrar": "to bury",
	"sepultar": "to bury",
	"gestionar": "to negotiate/manage",
	"jorobar": "to annoy",
	"rebajarse": "to lower oneself",
	"reñir": "to tell off",
	"silbar": "to whistle",
	"tachar": "to brand/accuse of",
	"tararear": "to hum",
	"acosar": "to harrass",
	"amparar": "to protect",
	"chillar": "to scream",
	"comparecer": "to appear in court",
	"denostar": "to insult",
	"encargar": "to order/put in charge of",
	"esfumarse": "to vanish",
	"increpar": "to rebuke",
	"prorrumpir": "to burst out",
	"refunfuñar": "to grumble",
	"resarcir": "to compensate",
	"reventar": "to burst",
	"abaratar": "to reduce",
	"acatar": "to comply with",
	"acolchar": "to pad",
	"acoplarse": "to fit together/dock",
	"afanarse": "to toil",
	"anonadar": "to stun",
	"aseverar": "to assert",
	"bostezar": "to yawn",
	"caber": "to be room for",
	"chapar": "to plate",
	"chiflarse": "to go crazy",
	"contrarrestar": "to counteract",
	"cotizar": "to quote",
	"demorar": "to delay/take time",
	"derretir": "to melt",
	"derrochar": "to squander",
	"derrotar": "to defeat",
	"descollar": "to stand out",
	"encorvar": "to bend",
	"enjuagar": "to rinse",
	"forrar": "to cover/upholster/line",
	"jactarse": "to boast",
	"mecerse": "to swing/rock",
	"musitar": "to mumble",
	"percatar": "to realize/notice",
	"pillar": "to catch",
	"pinchar": "to burst/puncture",
	"pirarse": "to take off",
	"pregonar": "to proclaim",
	"pulir": "to polish",
	"regañar": "to scold",
	"rematar": "to conclude",
	"subrayar": "to underline",
	"suplir": "to replace",
	"tallar": "to carve",
	"torcer": "to twist",
	"tragar": "to swallow",
	"vagar": "to wander",
	"abanderar": "to champion",
	"abastecer": "to supply",
	"abrasar": "to burn",
	"amarrar": "to tie",
	"arrobar": "to entrance",
	"blandir": "to brandish",
	"convenir": "to be advisable/agree",
	"copar": "to monopolize",
	"enganchar": "to hook",
	"enredarse": "to get tangled",
	"enroscar": "to screw/coil",
	"ensanchar": "to widen",
	"esmerarse": "to take great pains",
	"fregar": "to wash",
	"guisar": "to cook",
	"hender": "to split",
	"izar": "to raise",
	"jadear": "to pant",
	"limar": "to file down",
	"oprimir": "to oppress/weigh on",
	"patalear": "to stamp",
	"rascar": "to scratch",
	"remontar": "to overcome",
	"remontarse": "to date back",
	"aleccionar": "to instruct",
	"cabildear": "to lobby",
	"caducar": "to expire",
	"ceñirse": "to stick to",
	"desplazarse": "to move/travel",
	"dotar": "to equip with",
	"engreír": "to spoil/pamper",
	"escatimar": "to skimp on",
	"postergar": "to postpone",
	"pugnar": "to strive",
	"rebosar": "to overflow",
	"rezagar": "to delay",
	"zumbar": "to buzz",	
	"derribar": "to demolish",
	"aflojar": "to loosen",
	"agasajar": "to honor",
	"bucear": "to scuba dive",
	"desparramar": "to spill",
	"desviar": "to divert",
	"embadurnar": "to smear",
	"ensañar": "to enrage",
	"encandilar": "to dazzle",
	"esmerar": "to polish",
	"estornudar": "to sneeze",
	"gorjear": "to chirp",
	"graznar": "to caw",
	"rezongar": "to grumble",
	"raspar": "to scrape",
	"sonsacar": "to coax/extract",
	"timar": "to swindle",
	"trinchar": "to carve",
	"acurrucarse": "to curl up/snuggle",
	"amañar": "to rig",
	"asestar": "to deal",
	"cascar": "to crack",
	"currar": "to work",
	"despabilar": "to wake up",
	"estremecer": "to shudder",
	"forrarse": "to make a killing",
	"indagar": "to investigate",
	"prescindir": "to do without",
	"refrendar": "to endorse",
	"tejer": "to knit",
	"trastocar": "to disrupt",


	// NOUNS------------------------------------------------
	"el alce": "moose",
	"el andamiaje": "scaffolding",
	"el arete": "earring",
	"el asentamiento": "settlement",
	"el batido": "milkshake",
	"el blindaje": "armor-plating",
	"el camarote": "cabin",
	"el cartón": "cardboard",
	"el engrane": "cog",
	"el escaño": "bench/seat",
	"el estuche": "case",
	"el filón": "seam/vein/gold mine",
	"el hipo": "hiccups",
	"el imán": "magnet",
	"el marco": "frame",
	"el mostrador": "counter/desk",
	"el naipe": "playing card",
	"el payaso": "clown",
	"el puño": "fist",
	"el saldo": "account balance",
	"el señuelo": "decoy/bait",
	"el tapete": "rug",
	"el trance": "difficult situation",
    "el estío": "summer",
    "el arrebol": "red glow",
    "el ramo": "bouquet", 
    "el alambre": "wire",
    "el condado": "county",
    "el sueldo": "salary",
    "el estante": "shelf",
    "el delito": "crime",
    "el mito": "myth",
    "el desarrollo": "development",
    "el hallazgo": "discovery",
    "el dirigente": "leader",
    "el siglo": "century",
	"el bocado": "bite/snack",
	"el alimento": "food",
    "el lector": "reader",
    "el mueble": "furniture",
    "el puñado": "handful",
    "el apoyo": "support",
    "el plazo": "term/period",
    "el alfil": "bishop",
	"el obispo": "bishop",
	"el trastorno": "disorder",
	"el asunto": "issue",
	"el disfraz": "costume/disguise",
	"el concurso": "competition",
    "el ambito": "field/area/scope",
    "el alojamiento": "lodging",
    "el anfitrión": "host",
    "el suceso": "event",
	"el fondo": "bottom/back",
	"el desafío": "challenge",
	"el timbre": "doorbell",
	"el buzón": "mailbox",
	"el correo": "mail",
	"el vistazo": "peek/glance",
	"el ocio": "leisure",
	"el estacionamiento": "parking lot",	
	"el buque": "ship",
	"el esmoquin": "tuxedo",
	"el parqueo": "parking lot",	
	"el tenedor": "fork",
	"el camión": "truck",
	"el bolsillo": "pocket",
	"el ajedrez": "chess",
	"el folleto": "brochure",
    "el rastro": "trace",
    "el rasgo": "feature",
    "el riesgo": "risk",
    "el inmueble": "building/property",
    "el chiste": "joke",
    "el hueco": "hole",
	"el hoyo": "hole",
    "el techo": "ceiling/roof",
    "el sótano": "basement",
    "el rincón": "corner",
    "el ruido": "noise",
    "el racimo": "cluster",
    "el orgullo": "pride",
    "el suelo": "ground",
    "el ancho": "width",
    "el ladrillo": "brick",
    "el abanico": "fan",	
	"el maletín": "briefcase",
	"el amanecer": "dawn",
	"el matiz": "tinge/nuance",
	"el desempeño": "performance",	
	"el palo": "stick",
	"el revuelo": "stir/commotion",
	"el hilo": "thread",
	"el sendero": "path",	
	"el agujero": "hole",
	"el pedazo": "piece",
	"el taller": "workshop",
	"el sello": "stamp",
	"el lance": "incident",
	"el letrero": "sign/placard",
	"el capó": "hood",
	"el apodo": "nickname",
	"el almacén": "store",
	"el enano": "dwarf",
	"el reto": "challenge",
	"el ensayo": "essay/trial",	
	"el marfil": "ivory",
	"el plató": "set",	
	"el casco": "helmet",
	"el muro": "wall",
	"el gasto": "spending",
	"el entorno": "environment",
	"el filo": "edge",
    "el paso": "footstep",
    "el rumbo": "course/direction",
	"el caracol": "snail/seashell",
	"el cisne": "swan",
    "el gusano": "worm",
	"el venado": "deer",
	"el atardecer": "sunset",
	"el peñasco": "cliff",
    "el charco": "puddle",
    "el yermo": "barren/wasteland",
    "el pasto": "grass",
    "el trigo": "wheat",
    "el crepúsculo": "dusk",
    "el nido": "nest",
    "el trueno": "thunder",
    "el estanque": "pond",
    "el barro": "mud",
    "el lodo": "mud",
    "el sostén": "bra",
	"el ceño": "brow",	
	"el pulgar": "thumb",
	"el tobillo": "ankle",
	"el ombligo": "navel",
    "el rostro": "face",
	"el escombro": "rubble/debris",
	"el acero": "steel",
	"el resquicio": "crack",
	"el guion": "script",
	"el caudillo": "military leader",
	"el estruendo": "loud crash/boom",
	"el colibrí": "hummingbird",
	"el pulpo": "octopus",
	"el alud": "avalanche/landslide",
	"el rebaño": "flock",
	"el ganado": "livestock",
	"el lecho": "bed",
	"el arroyo": "stream",
	"el semáforo": "traffic light",
	"el tiburón": "shark",
	"el llanto": "crying",
	"el molino": "mill",
	"el vagón": "passenger car",
	"el balde": "bucket",
	"el trozo": "piece",
	"el rocío": "dew",
	"el huésped": "guest",
	"el indulto": "pardon",
	"el juzgado": "court",
	"el juicio": "trial",
	"el juez": "judge",
	"el casero": "landlord",
	"el inquilino": "tenant",
	"el perchero": "coat stand",
	"el desgaste": "wear",
	"el asedio": "siege",
	"el atisbo": "trace",
	"el hongo": "mushroom",
	"el sillón": "armchair",
	"el cascarrabias": "grouch",
	"el cascarrabias": "grouch",
	"el desprecio": "contempt",
	"el gorro": "cap",
	"el meollo": "heart",
	"el solterón": "confirmed bachelor",
	"el arco": "goal",
	"el regocijo": "joy",
	"el brote": "sprout/outbreak",
	"el menoscabo": "reduction",
	"el volante": "steering wheel",
	"el fregadero": "kitchen sink",
	"el duende": "pixie",
	"el césped": "lawn/grass",
	"el tazón": "bowl",
	"el ratraco": "robbery",
	"el compinche": "buddy/accomplice",
	"el botín": "plunder",
	"el chaleco": "vest",
	"el hueso": "bone",
	"el musgo": "moss",
	"el yerro": "error",
	"el hierro": "iron",
	"el rendimiento": "performance",
	"el carril": "lane",
	"el chicle": "chewing gum",
	"el cimiento": "foundation",
	"el embuste": "lie",
	"el enlace": "link",
	"el fideo": "noodle",
	"el foso": "pit/ditch",
	"el hígado": "liver",
	"el manto": "cloak",
	"el patrón": "boss/pattern",
	"el pincel": "paintbrush",
	"el presupuesto": "budget",
	"el recorrido": "trip",
	"el socio": "member",
	"el vitral": "stained-glass window",
	"el acervo": "heritage",
	"el ánimo": "mood",
	"el bajón": "slump",
	"el calabozo": "jail",
	"el colchón": "mattress",
	"el comensal": "dinner guest",
	"el costal": "sack",
	"el dispositivo": "device",
	"el eje": "axis",
	"el embudo": "funnel",
	"el gerente": "manager",
	"el gremio": "profession",
	"el hito": "milestone",
	"el hollín": "soot",
	"el legado": "legacy",
	"el manantial": "spring/source",
	"el mitin": "rally",
	"el pavor": "dread",
	"el pliegue": "fold",
	"el rebozo": "shawl",
	"el requisito": "requirement",
	"el retraso": "delay",
	"el sigilo": "stealth",
	"el tramo": "stretch/section",
	"el yeso": "plaster",
	"el acertijo": "riddle",
	"el aliento": "breath",
	"el apego": "attachment",
	"el azar": "chance/fate",
	"el bicho": "bug/critter",
	"el bribón": "rascal",
	"el brocal": "rim",
	"el búho": "owl",
	"el cajón": "drawer",
	"el caldo": "broth",
	"el caucho": "rubber",
	"el cerezo": "cherry tree",
	"el cónyuge": "spouse",
	"el corro": "ring/circle",
	"el cubo": "bucket",
	"el cuero": "leather",
	"el elenco": "cast",
	"el farol": "lantern",
	"el garabato": "scribble",
	"el guijarro": "pebble",
	"el hedor": "stench",
	"el infarto": "heart attack",
	"el jaque": "check/threat",
	"el lema": "motto",
	"el lineamiento": "guideline",
	"el mozo": "young boy/young girl",
	"el pantano": "swamp",
	"el procurador": "attorney",
	"el pulmón": "lung",
	"el suegro": "father-in-law",
	"el suministro": "supply",
	"el tejido": "fabric/tissue",
	"el telón": "curtain",
	"el telón de fondo": "backdrop",
	"el tino": "sound judgment/tact",
	"el umbral": "threshold",
	"el verdugo": "executioner",
	"el yerno": "son-in-law",
	"el aposento": "lodging/room",
	"el disparate": "nonsense",
	"el esparcimiento": "recreation",
	"el lirio": "lily",
	"el púbero": "adolescent",
	"el quehacer": "chore",
	"el sentido": "sense/meaning",
	"el séquito": "entourage",
	"el acantilado": "cliff",
	"el brío": "spirit/verve",
	"el bucle": "curl/loop",
	"el buey": "ox",
	"el callejón": "alley",
	"el glóbulo": "blood cell",
	"el listón": "strip",
	"el nudillo": "knuckle",
	"el pañal": "diaper",
	"el pastor": "shepherd",
	"el rascacielos": "skyscraper",
	"el regazo": "lap",
	"el reno": "reindeer",
	"el tapiz": "tapestry",
	"el títere": "puppet",
    "el ajetreo": "hustle and bustle",
    "el antojo": "craving",
    "el cuello": "neck",
    "el durazno": "peach",
    "el espejismo": "mirage/illusion",
    "el faro": "lighthouse/beacon",
    "el lío": "mess",
    "el litoral": "coast",
    "el ovillo": "ball",
    "el padrino": "godfather",
    "el puchero": "cooking pot",
    "el roble": "oak",
    "el rubor": "blush",
    "el secuaz": "follower",
    "el tejado": "roof",
    "el tonel": "barrel",
    "el vidrio": "glass",
    "el bramante": "twine",
    "el chorro": "stream",
    "el reparto": "distribution/delivery",
    "el rompecabezas": "puzzle",
    "el ventarrón": "strong wind",
	"el jorobado": "hunchback",
	"el moho": "mold",
	"el olimpo": "pantheon",
	"el paradero": "whereabouts",
	"el peldaño": "step/rung",
	"el proceder": "behavior",
	"el romero": "rosemary",
	"el rubro": "area",
	"el soborno": "bribe",
	"el tirón": "pull",
	"el trineo": "sled",
	"el asno": "donkey",
	"el borde": "edge",
	"el cobre": "copper",
	"el escudo": "shield",
	"el vellón": "fleece",
	"el albañil": "builder",
	"el algodón": "cotton",
	"el almidón": "starch",
	"el ataúd": "coffin",
	"el buitre": "vulture",
	"el canalón": "gutter",
	"el cáñamo": "hemp",
	"el chaval": "kid",
	"el ciervo": "deer",
	"el cojín": "cushion",
	"el desenlace": "ending/outcome",
	"el empeño": "determination",
	"el encaje": "lace",
	"el envoltorio": "wrapper",
	"el fango": "mud",
	"el fogón": "stove",
	"el garrafón": "water jug",
	"el grifo": "faucet",
	"el hechizo": "spell",
	"el luto": "mourning",
	"el paraje": "place",
	"el pepino": "cucumber",
	"el polluelo": "chick",
	"el préstamo": "loan",
	"el pringado": "loser",
	"el riachuelo": "brook/stream",
	"el riñón": "kidney",
	"el rollo": "roll/story",
	"el sesgo": "bias",
	"el sorbo": "sip",
	"el tacón": "heel",
	"el adiestramiento": "training",
	"el álamo": "poplar",
	"el avellano": "hazel",
	"el cenote": "natural well",
	"el chivato": "informer",
	"el cuervo": "crow/raven",
	"el derredor": "perimeter",
	"el desfile": "parade",
	"el enjambre": "swarm",
	"el estrago": "damage",
	"el féretro": "coffin",
	"el frasco": "bottle/jar",
	"el helecho": "fern",
	"el hormigón": "concrete",
	"el lebrel": "greyhound",
	"el matón": "thug",
	"el pordiosero": "beggar",
	"el rodaje": "shooting/filming",
	"el vástago": "offspring",
	"el vato": "dude",
	"el vertedero": "garbage dump",
	"el grupo etario": "age group",
	"el adalid": "champion",
	"el ademán": "gesture",
	"el asiento": "seat",
	"el atasco": "blockage/traffic jam",
	"el champiñon": "mushroom",
	"el colmo": "height",
	"el cuartel": "barracks",
	"el estandarte": "banner",
	"el follón": "mess",
	"el forajido": "outlaw",
	"el guiño": "wink",
	"el hincapié": "emphasis",
	"el montículo": "hillock",
	"el lazo": "bow/tie/knot/link",
	"el penique": "penny",
	"el relámpago": "lightning",
	"el surco": "furrow",
	"el tropiezo": "stumble/setback",
	"el bidón": "barrel/can",
	"el brebaje": "potion/concoction",
	"el chavo": "guy",
	"el cortijo": "country house",
	"el desfiladero": "gorge",
	"el entramado": "framework",
	"el estiércol": "manure",
	"el higo": "fig",
	"el matorral": "thicket",
	"el paleto": "hick/redneck",
	"el tronco": "trunk/log",
	"el adoquín": "paving stone",
	"el afán": "eagerness",
	"el aplomo": "composure",
	"el atuendo": "attire",
	"el carrillo": "cheek",
	"el cebo": "bait",
	"el cenicero": "ashtray",
	"el chollo": "bargain",
	"el cincel": "chisel",
	"el ermitaño": "hermit",
	"el esmero": "care/diligence",
	"el fieltro": "felt",
	"el fragor": "clamor",
	"el galán": "handsome man",
	"el manjar": "delicacy", 
	"el maricón": "queer",
	"el paño": "cloth",
	"el nudo": "knot",
	"el pormenor": "detail",
	"el pudor": "modesty",
	"el remo": "oar",
	"el remanso": "haven",
	"el soplido": "puff",
	"el sosiego": "calm",
	"el vaivén": "swaying",	
	"el alfiler": "pin",
	"el barranco": "ravine",
	"el bulo": "false rumor",
	"el caudal": "flow/wealth",
	"el cencerro": "cowbell",
	"el desvelo": "sleeplessness",
	"el huerto": "orchard/veg garden",
	"el lomo": "back",
	"el mentón": "chin",
	"el peregrino": "pilgrim",
	"el pezón": "nipple",
	"el retoño": "sprout/kid",
	"el tropel": "mob",	
	"los desvelos": "efforts",
	"los comicios": "elections",
	"los entresijos": "ins and outs",
	"los nietos": "grandchildren",

	
	"la ceniza": "ash",
    "la cerca": "fence",
    "la granja": "farm",
    "la plata": "silver",
    "la meta": "goal/objective",
    "la nave": "ship",
	"la hoz": "sickle",
	"la botana": "snack",
    "la jaula": "cage",
    "la herramienta": "tool",
    "la espada": "sword",
    "la pieza": "piece",
    "la viuda": "widow",
	"la prensa": "press",
	"la talla": "size",
    "la bala": "bullet",
    "la huelga": "strike",
    "la condena": "sentence",
    "la trama": "plot",
    "la ducha": "shower",
    "la tasa": "rate/tax",
	"la aldea": "small village",
	"la pifia": "blunder",
	"la mentira": "lie",
	"la arruga": "wrinkle",
	"la gaveta": "drawer",
	"las joyas": "jewels",
	"la banca": "bench",
	"la cautela": "caution",
	"la pegatina": "sticker",
	"la calidez": "warmth",
	"la alfombra": "carpet",
    "la finca": "property",
	"la broma": "joke",
    "la pared": "wall",
    "la brizna": "strand",
    "la ley": "law",
    "la rueda": "wheel",
    "la huella": "footprint",
    "la fracasa": "failure",
    "la dicha": "happiness",
    "la cita": "meeting/date",
    "la viga": "rafter",
    "la aguja": "needle",
	"la oración": "sentence",
	"la pastilla": "pill",
	"la puesta": "setting",
	"la víspera": "eve/night before",
	"la gama": "range/spectrum",
	"la gira": "tour",
	"la saña": "malice",
	"la triza": "piece",
	"la grúa": "tow truck",
	"la pandilla": "gang",
	"la cancha": "court/playing area",
	"la trampa": "trap",
	"la etiqueta": "tag/label",
	"la sabiduría": "wisdom",
	"la malla": "mesh",
	"la secuela": "consequence",
	"la cuna": "crib/cradle",
	"la navaja": "razor",
	"la minorista": "retail",
	"la bombilla": "light bulb",
	"la acera": "sidewalk",
	"la oruga": "caterpillar",
	"la oveja": "sheep",
	"la ardilla": "squirrel",
	"la selva": "jungle",
	"la rabia": "anger/rage",
	"la encimera": "counter",
	"la ferretería": "hardware store",
	"la fuga": "leak",
	"la garra": "claw",
	"la tina": "bathtub",
	"la foca": "seal",
	"la ladera": "slope",
	"la grasa": "fat/grease",
	"la grieta": "crack",
	"la niñera": "babysitter",
	"la incertidumbre": "uncertainty",
	"la aurora": "dawn",
	"la hembra": "female",
	"la solterona": "spinster",
	"la soltera": "single woman",
	"la cobija": "blanket",
	"la tetera": "teapot",
	"la escoba": "broom",
	"la mueca": "grimace",
	"la burbuja": "bubble",
	"la propina": "tip",
	"la etapa": "period",
	"la bata": "robe",
	"la tregua": "truce/respite",
	"la flota": "fleet",
	"la brújula": "compass",
	"la hada": "fairy",
	"la olla": "pot",
	"la tecla": "key",
	"la codicia": "greed",
	"la seta": "mushroom",
	"la loma": "hill",
	"la factura": "invoice",
	"la etapa": "period",
	"la arenisca": "sandstone",
	"la choza": "hut",
	"las ganas": "desire",
	"la guarida": "den/hideout/lair",
	"la harina": "flour",
	"la leña": "firewood",
	"la orilla": "shore",
	"la punzada": "pang/prick",
	"la rienda": "rein",
	"la sequía": "drought",
	"la cosecha": "harvest/crop",
	"la ballena": "whale",
	"la baya": "berry",	
	"la colina": "hill",
    "la niebla": "fog",
    "la raíz": "root",
    "la hoja": "leaf",
    "la maleza": "weeds",
    "la madrugada": "dawn",
    "la pradera": "prairie/meadow",
    "la amapola": "poppy",
    "la yedra": "ivy",
	"la manga": "sleeve",
	"la prenda": "garment",
	"la axila": "armpit",
	"la ceguera": "blindness",
	"la mejilla": "cheek",
	"la panza": "belly",
	"la ceja": "eyebrow",
    "la uña": "nail",
	"la arcilla": "clay",
	"la calabaza": "pumpkin",
	"la furgoneta": "van",
	"la hipoteca": "mortgage",
	"la jubilación": "retirement",
	"la lana": "wool",
	"la lápida": "tombstone",
	"la nalga": "butt",
	"la redada": "raid",
	"la vejación": "humiliation",
	"la abolladura": "dent",
	"la barriga": "stomach",
	"la brisa": "breeze",
	"la cabida": "capacity/room/space",
	"la cabra": "goat",
	"la carencia": "scarcity",
	"la caspa": "dandruff",
	"la chispa": "spark",
	"la colcha": "bedspread",
	"la comisaría": "police station",
	"la desgracia": "misfortune/tragedy",
	"la estafa": "fraud",
	"la fiera": "wild beast",
	"la horca": "gallows/pitchfork",
	"la lumbre": "fire/light",
	"la maldición": "curse",
	"la maña": "skill",
	"la mancha": "stain/spot",
	"la manta": "blanket",
	"la misa": "mass",
	"la morada": "dwelling",
	"la pala": "shovel",
	"la posada": "inn",
	"la ráfaga": "gust/flash",
	"la reja": "bars",
	"la rendija": "crack",
	"la ternura": "tenderness",
	"la zancada": "stride",
	"la zozobra": "anxiety",
	"la franja": "stripe",
	"la vela": "candle",	
	"la acuarela": "watercolor",
	"la afición": "fondness",
    "la cola": "tail",
    "la faena": "task",
    "la golosina": "candy",
    "la greda": "clay",
    "la nuez": "nut",
    "la pisada": "footstep/footprint",
    "la taquilla": "box office",	
	"la hazaña": "feat",
	"la liebre": "hare",
	"la linterna": "flashlight",
	"la migaja": "crumb",
	"la pestaña": "eyelash",
	"la senda": "path",   
	"la aduana": "customs",
	"la avena": "oatmeal",
	"la bandeja": "tray",
	"la bandeja de entrada": "inbox",
	"la cabalidad": "completeness",
	"la carpeta": "folder",
	"la cáscara": "shell",
	"la cinta": "ribbon/film",
	"la contienda": "conflict",
	"la cordura": "sanity/good sense",
	"la correa": "strap/leash",
	"la loseta": "floor tile",
	"la manada": "herd",
	"la nuera": "daughter-in-law",
	"la pechuga": "breast",
	"la repisa": "shelf",
	"la salvia": "sage",
	"la vitrina": "glass case",
	"la carcajada": "loud laugh",
	"la casaca": "jacket",
	"la charca": "pond",
	"la costilla": "rib",
	"la jauría": "pack",
	"la acotación": "marginal note",
	"la ampolla": "blister/vial",
	"la arveja": "pea",
	"la babosa": "slug",
	"la baraja": "deck of cards",
	"la báscula": "scale",
	"la beca": "scholarship/grant",
	"la bellota": "acorn",
	"la bolsa de valores": "stock exchange",
	"la chacha": "maid",
	"la ebullición": "boil/turmoil",
	"la fusta": "whip",
	"la gamuza": "suede",
	"la ganga": "bargain",
	"la hondonada": "hollow",
	"la hormiga": "ant",
	"la jornada": "workday",
	"la lavandina": "bleach",
	"la lechuza": "barn owl",
	"la madrastra": "stepmother",
	"la osadía": "boldness",
	"la paja": "straw/hay",
	"la planta": "sole",
	"la racha": "streak",
	"la rebanada": "slice",
	"la regadera": "shower",
	"la sandía": "watermelon",
	"la seda": "silk",
	"la soberbia": "pride",
	"la sucursal": "branch office",
	"la tela": "fabric",
	"la tripulación": "crew",
	"la alacena": "cupboard",
	"la alimaña": "pest",
	"la bronca": "fight",
	"la cadera": "hip",
	"la desazón": "unease",
	"la desidia": "carelessness",
	"la especia": "spice",
	"la gentuza": "riffraff",
	"la gestión": "management",
	"la lata": "can",
	"la lupa": "magnifying glass",
	"la manguera": "hose",
	"la maniobra": "maneuver",
	"la melena": "long hair",
	"la novedad": "news",
	"la portada": "cover",
	"la tanda": "series",
	"la tesón": "tenacity",
	"la tripa": "intestine/gut/insides",
	"la valla": "fence",
	"la vejiga": "bladder",
	"la viruta": "shaving",
	"la zanja": "ditch",
	"la colmena": "beehive",
	"la cuenca": "basin",
	"la franquisia": "franchise",
	"la maceta": "flowerpot",
	"la morsa": "walrus",
	"la paliza": "beating",
	"la penumbra": "half-light",
	"la pesquisa": "inquiry",
	"la tachuela": "thumbtack",
	"la trucha": "trout",
	"la vasija": "pot",
	"la alcoba": "bedroom",
	"la arroba": "@",
	"la atalaya": "watchtower/lookout",
	"la avería": "breakdown",
	"la bajeza": "vile deed",
	"la barra": "bar/slash",
	"la butaca": "armchair/seat",
	"la cana": "grey hair",
	"la cantera": "quarry",
	"la deriva": "drift",
	"la epopeya": "epic",
	"la escalinata": "staircase",
	"la estancia": "stay",
	"la estirpe": "lineage",
	"la gaviota": "seagull",
	"la herradura": "horseshoe",
	"la neblina": "mist",
	"la papila": "bud",
	"la quiebra": "bankruptcy",
	"la tarrina": "tub",
	"la traba": "obstacle",
	"la ventisca": "blizzard",
	"la acequia": "irrigation ditch",
	"la adelfa": "oleander",
	"la escopeta": "shotgun",
	"la mota": "speck",
	"la pocilga": "pigsty",
	"la ribera": "riverbank",
	"la esquina": "corner",
	"la barbilla": "chin",
	"la cepa": "stock/vine",
	"la cerilla": "earwax/match",
	"la gabardina": "raincoat",
	"la mofa": "mockery",
	"la pleitesía": "respect",
	"la pulgada": "inch",
	"la quijada": "jaw",
	"la ranura": "slot",
	"la sarta": "string",
	"la tapadera": "lid/front",
	"la aleta": "fin",
	"la braga": "panties",
	"la ínfula": "pretension",
	"la llanura": "plain",
	"la lombriz": "worm",
	"la marmita": "pot",
	"la porquería": "junk/filth",
	"la resaca": "hangover",
	"la ristra": "string",
	"la onda": "ripple",
	"la ola": "wave",
	"la oleada": "wave/mass occurrence",
	"la camioneta": "van",
    "las moscas": "flies",	
	"el águila": "eagle",
	"el alba": "dawn",
	"el alza": "rise",
	"el aula": "classroom",
}


var reviewWords = {
	
	// "el padrino": "godfather",
	// "la madrina": "godmother",
	// "el ahijado": "godson",
	// "la ahijada": "goddaughter",
	
	// "el padrastro": "stepfather",
	// "la madrastra": "stepmother",
	// "el hijastro": "stepson",
	// "la hijastra": "stepdaughter",
	// "el hermanastro": "stepbrother",
	// "la hermanastra": "stepsister",
	
	// "el suegro": "father-in-law",
	// "la suegra": "mother-in-law",
	// "el yerno": "son-in-law",
	// "la nuera": "daughter-in-law",
	// "el cuñado": "brother-in-law",
	// "la cuñada": "sister-in-law",
	
	// "el sobrino": "nephew",
	// "la sobrina": "niece",
	// "el nieto": "grandson",
	// "la nieta": "granddaughter",
	
	
	// "burdo": "clumsy",
	// "torpe": "clumsy",
	// "hosco": "sullen",
	// "tosco": "crude",
	// "terco": "stubborn",

	// "cosquillear": "to tickle",
	// "coquetear": "to flirt",
	// "cotillear": "to gossip",
	// "chismear": "to gossip",
	"estrepitoso": "spectacular/noisy",
	// "espantoso": "horrifying",
	// "espeluznante": "terrifying",
	// "la sabiduría": "wisdom",
	// "la soberbia": "pride",
	"la hoja": "leaf",
	"la mano": "hand",

	
}

//Once you have these down, move them to the "reviewWords" list, then eventually to the "old" list
var currentWords = {
	
	"acogedor": "cozy",
	"de reojo": "out of the corner of the eye",
	"descalzo": "barefoot",
	"enclenque": "sickly/weak",
	"mohoso": "moldy",
	"morado": "purple",
	
	"agacharse": "to crouch",
	"agazaparse": "to crouch",
	"amortiguar": "to cushion/absorb",
	"bramar": "to bellow",
	"chamuscar": "to scorch/singe",
	"escurrir": "to wring out/drain",
	"espejear": "to shimmer",
	"husmear": "to sniff",
	"rastregar": "to scrub",
	"sobrellevar": "to endure",
	"surtir": "to supply",

	"el apuro": "predicament/embarrassment",	
	"el aspersor": "sprinkler",
	"el bastón": "cane",
	"el batiburrillo": "jumble",
	"el boceto": "sketch",
	"el botiquín": "medicine cabinet/first-aid kit",
	"el bufido": "snort",
	"el camposanto": "cemetery",
	"el codo": "elbow",
	"el esbozo": "sketch",
	"el fajo": "wad/bundle",
	"el lienzo": "canvas",
	"el pañuelo": "handkerchief/scarf",
	"el mechero": "lighter",
	"el pelele": "ragdoll",
	"el pomo": "knob/handle",
	"el puñal": "dagger",
	"el retintín": "ringing/sarcasm",
	"el riego": "irrigation",
	"el rótulo": "label",
	"el tablón": "plank",
	"el trámite": "process",
	"el trapo": "rag",
	
	"la balsa": "raft",
	"la bufanda": "scarf",
	"la bisagra": "hinge",
	"la caliza": "limestone",
	"la calavera": "skull",
	"la cera": "wax",
	"la comezón": "itching",
	"la muñeca": "wrist",
	"la lentilla": "contact lense",
	"la perilla": "goatee/knob",
	"la pértiga": "pole",
	"la tiniebla": "darkness",
	"el ancla": "anchor",
	
	
	"quemarropa": "close range",
	"acuciante": "urgent",
	"adrede": "on purpose",
	"otrora": "formerly",
	"por doquier": "everywhere",
	"recóndito": "remote/hidden",
	
	"cebar": "to fatten/fuel",
	"chupar": "to suck",
	"cuchichear": "to whisper",
	"desamparar": "to abandon",
	"hurgar": "to rummage",
	
	"el alféizar": "windowsill",
	"el chamán": "shaman",
	"el desamparo": "neglect",
	"el ferrocarril": "railroad",
	"el percance": "mishap",
	"el retrete": "toilet",
	"el visón": "mink",
	"los sesos": "brains",
	
	"la alondra": "lark",
	"la azafata": "flight attendant",
	"la hecatombe": "disaster",
	"la pantufla": "slipper",
	"la premura": "haste",
	"la tabla": "board",
	
}

var onDeck = {
	
	"quienquiera": "whoever",
	
	"el cobijo": "shelter",
	"el esbirro": "henchman",
	
	"la campiña": "countryside",
	"la coartada": "alibi",
	"la vocal": "vowel",
	"las habladurías": "rumors",

	
}